In [1]:
import pandas as pd

In [2]:
df_yt = pd.read_csv('ytb_context_paragraph.csv')
df_tt = pd.read_csv('tiktok_content_paragraph.csv')
df = pd.read_csv('comment_cleaned_revised.csv')

In [3]:
df_tt.head()

,Video ID,Tiêu đề Video,Nội dung chính toàn video,Các điểm nhấn/Tranh cãi (Key Highlights),Sắc thái chủ đạo (Target Sentiment)
0,7619505128890010901,Hai người mẫu quay quảng cáo trong show thực tế,"Video là một đoạn cắt từ chương trình thực tế,...",Bối cảnh studio tối giản; hai người mẫu đọc lờ...,Giải trí / tình huống vụng về
1,7622268970770500885,Tổng hợp drama mạng xã hội về TikToker Lê Xuân...,Video thuộc dạng talking head kết hợp reaction...,Dạng talking head kết hợp reaction; sử dụng sp...,Phê phán / tranh cãi mạng xã hội
2,7625986583996402965,Màn hình tin nhắn cũ gợi lại ký ức tình yêu,Video ghi lại màn hình cuộc trò chuyện Messeng...,Giao diện Messenger bị làm mờ; thao tác cuộn t...,Trầm buồn / hoài niệm
3,7627477139138301202,Slideshow tin nhắn cặp đôi với cách trả lời ng...,Video là một slideshow gồm các ảnh chụp màn hì...,Slideshow ảnh chụp tin nhắn; meme chim cánh cụ...,Giải trí / tình cảm đời sống
4,7628064166992973077,Cắt ghép phóng sự lớp học về bé Phương Anh và ...,Video là bản cắt ghép từ một phóng sự lớp học ...,Bối cảnh lớp học giờ ăn bán trú; cô giáo gọi b...,Giải trí / tình huống học đường

In [4]:
df_tt['Video ID'] = df_tt['Video ID'].astype(object)

In [5]:
df_tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Video ID                                  12 non-null     object
 1   Tiêu đề Video                             12 non-null     object
 2   Nội dung chính toàn video                 12 non-null     object
 3   Các điểm nhấn/Tranh cãi (Key Highlights)  12 non-null     object
 4   Sắc thái chủ đạo (Target Sentiment)       12 non-null     object
dtypes: object(5)
memory usage: 612.0+ bytes

In [6]:
df_yt.head()

,Video ID,Tiêu đề Video,Nội dung chính toàn video,Các điểm nhấn/Tranh cãi (Key Highlights),Sắc thái chủ đạo (Target Sentiment)
0,5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến toàn bộ trận đấu bóng đá kịch tính g...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng
1,yM8XxAwUM_M,GIẤY GHI CHÚ TÂM NGUYỆN,Màn trình diễn ca khúc 'Giấy ghi chú tâm nguyệ...,"Sự kết hợp giữa các nghệ sĩ Lý Tiểu Nhiễm, Đườ...",Tích cực (Positive)
2,HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,"Giải thích về trường phái lập thể, các giai đo...",Châm biếm / Giáo dục (Satirical/Educational)
3,toJjgQgBwx0,Vạch Trần Toàn Bộ Chiêu Trò Của Gia Đình Tai T...,Video phân tích và bóc phốt dài gần 1 tiếng củ...,"Giả giới tính (Thục San), tin đồn ""luận"" giữa ...",Tiêu cực / Phê phán (Negative/Critical)
4,fnTfJ130mjw,Tất cả những trend đần độn nhất trên mạng xã h...,Video bình luận mang giọng điệu mỉa mai và hài...,"Phân tích sự biến tướng của trào lưu ""Healing""...",Mỉa mai / Châm biếm (Sarcastic/Satirical)

In [7]:
df_yt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Video ID                                  8 non-null      object
 1   Tiêu đề Video                             8 non-null      object
 2   Nội dung chính toàn video                 8 non-null      object
 3   Các điểm nhấn/Tranh cãi (Key Highlights)  8 non-null      object
 4   Sắc thái chủ đạo (Target Sentiment)       8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes

In [8]:
df.head()

,platform,video_id,video_url,video_title,video_core_content,video_target_sentiment,video_cultural_context,uploader,upload_date,view_count,...,share_count,duration_seconds,comment_id,comment_author,comment_author_id,comment_like_count,comment_reply_count,comment_create_time,index_goc,comment
0,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,"Kể về cuộc đời, sự nghiệp nghệ thuật và những ...",neutral,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1648.0,bác pi cát xô là bạn của bác hồ
1,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,"Kể về cuộc đời, sự nghiệp nghệ thuật và những ...",neutral,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1649.0,cấm sừng nhiều thế
2,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,"Kể về cuộc đời, sự nghiệp nghệ thuật và những ...",neutral,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1650.0,cho ai chưa biết thì những người đó đều là nic...
3,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,"Kể về cuộc đời, sự nghiệp nghệ thuật và những ...",neutral,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1651.0,tên bài nhạc là gì vậy mọi người
4,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,"Kể về cuộc đời, sự nghiệp nghệ thuật và những ...",neutral,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1652.0,picasso năm 10 14t đẹp trai vãi

In [9]:
df_tt.columns

Index(['Video ID', 'Tiêu đề Video', 'Nội dung chính toàn video',
       'Các điểm nhấn/Tranh cãi (Key Highlights)',
       'Sắc thái chủ đạo (Target Sentiment)'],
      dtype='object')

In [10]:
df_yt.columns

Index(['Video ID', 'Tiêu đề Video', 'Nội dung chính toàn video',
       'Các điểm nhấn/Tranh cãi (Key Highlights)',
       'Sắc thái chủ đạo (Target Sentiment)'],
      dtype='object')

In [11]:
df.columns

Index(['platform', 'video_id', 'video_url', 'video_title',
       'video_core_content', 'video_target_sentiment',
       'video_cultural_context', 'uploader', 'upload_date', 'view_count',
       'like_count', 'comment_count', 'share_count', 'duration_seconds',
       'comment_id', 'comment_author', 'comment_author_id',
       'comment_like_count', 'comment_reply_count', 'comment_create_time',
       'index_goc', 'comment'],
      dtype='object')

In [12]:
df[df['platform'] == 'tiktok']['video_id']

1304    7.62E+18
1305    7.62E+18
1306    7.62E+18
1307    7.62E+18
1308    7.62E+18
          ...
7775    7.63E+18
7776    7.63E+18
7777    7.63E+18
7778    7.63E+18
7779    7.63E+18
Name: video_id, Length: 2895, dtype: object

In [13]:
tiktok_ids = df['video_url'].str.extract(r'/video/(\d+)', expand=False)
df.loc[df['platform'] == 'tiktok', 'video_id'] = tiktok_ids

In [14]:
print(df[df['platform'] == 'youtube']['video_id'].nunique())
print(df_yt['Video ID'].nunique())
print(df[df['platform'] == 'tiktok']['video_id'].nunique())
print(df_tt['Video ID'].nunique())

7
8
12
12

In [15]:
df[df['platform'] == 'tiktok']['video_id']

1304    7619505128890010901
1305    7619505128890010901
1306    7619505128890010901
1307    7619505128890010901
1308    7619505128890010901
               ...
7775    7628963437556665620
7776    7628963437556665620
7777    7628963437556665620
7778    7628963437556665620
7779    7628963437556665620
Name: video_id, Length: 2895, dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7978 entries, 0 to 7977
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   platform                7978 non-null   object
 1   video_id                7978 non-null   object
 2   video_url               7978 non-null   object
 3   video_title             7978 non-null   object
 4   video_core_content      7978 non-null   object
 5   video_target_sentiment  7978 non-null   object
 6   video_cultural_context  2400 non-null   object
 7   uploader                2895 non-null   object
 8   upload_date             2895 non-null   float64
 9   view_count              2895 non-null   float64
 10  like_count              2895 non-null   float64
 11  comment_count           2895 non-null   float64
 12  share_count             2895 non-null   float64
 13  duration_seconds        2895 non-null   float64
 14  comment_id              2895 non-null   float64
 15  comment_author          2895 non-null   object
 16  comment_author_id       2895 non-null   float64
 17  comment_like_count      2895 non-null   float64
 18  comment_reply_count     2895 non-null   float64
 19  comment_create_time     2895 non-null   object
 20  index_goc               6390 non-null   float64
 21  comment                 7975 non-null   object
dtypes: float64(11), object(11)
memory usage: 1.3+ MB

In [17]:
df =  df[['platform', 'video_id', 'video_url', 'video_title',
          'video_core_content','video_target_sentiment','comment']]
df_tt = df_tt[['Video ID', 'Nội dung chính toàn video',
       'Các điểm nhấn/Tranh cãi (Key Highlights)']]
df_yt = df_yt[['Video ID', 'Nội dung chính toàn video',
       'Các điểm nhấn/Tranh cãi (Key Highlights)']]

In [18]:
df_tt['Video ID'] = df_tt['Video ID'].astype(str)
df_yt['Video ID'] = df_yt['Video ID'].astype(str)
df['video_id'] = df['video_id'].astype(str)

In [19]:
df_combined = pd.concat([df_tt, df_yt], ignore_index=True)

Core_content = df_combined.set_index('Video ID')['Nội dung chính toàn video']
highlight = df_combined.set_index('Video ID')['Các điểm nhấn/Tranh cãi (Key Highlights)']
df['video_core_content'] = df['video_id'].map(Core_content)
df['video_highlight'] = df['video_id'].map(highlight)

In [20]:
df_combined.head()

,Video ID,Nội dung chính toàn video,Các điểm nhấn/Tranh cãi (Key Highlights)
0,7619505128890010901,"Video là một đoạn cắt từ chương trình thực tế,...",Bối cảnh studio tối giản; hai người mẫu đọc lờ...
1,7622268970770500885,Video thuộc dạng talking head kết hợp reaction...,Dạng talking head kết hợp reaction; sử dụng sp...
2,7625986583996402965,Video ghi lại màn hình cuộc trò chuyện Messeng...,Giao diện Messenger bị làm mờ; thao tác cuộn t...
3,7627477139138301202,Video là một slideshow gồm các ảnh chụp màn hì...,Slideshow ảnh chụp tin nhắn; meme chim cánh cụ...
4,7628064166992973077,Video là bản cắt ghép từ một phóng sự lớp học ...,Bối cảnh lớp học giờ ăn bán trú; cô giáo gọi b...

In [21]:
Core_content

Video ID
7619505128890010901    Video là một đoạn cắt từ chương trình thực tế,...
7622268970770500885    Video thuộc dạng talking head kết hợp reaction...
7625986583996402965    Video ghi lại màn hình cuộc trò chuyện Messeng...
7627477139138301202    Video là một slideshow gồm các ảnh chụp màn hì...
7628064166992973077    Video là bản cắt ghép từ một phóng sự lớp học ...
7628089059503590677    Video tổng hợp các phân cảnh biểu diễn ca khúc...
7628192889352293653    Video kể lại câu chuyện về quán lẩu gà Mạc Thị...
7628428855467871508    Video là một skit ngắn trong phòng, trong đó h...
7628678480326135060    Video thuộc dạng Q&A/talking head, trong đó mộ...
7628876598191623432    Video sử dụng các meme mèo được cắt ghép trên ...
7628919104874892562    Video là một đoạn talking head kết hợp skit tạ...
7628963437556665620    Video ngắn giới thiệu ngoại hình và phong cách...
5Augh75jX6g            Diễn biến toàn bộ trận đấu bóng đá kịch tính g...
yM8XxAwUM_M            Màn trình diễn ca khúc 'Giấy ghi chú tâm nguyệ...
HyDxRTBnwNM            Video hoạt hình vẽ tay mang phong cách hài hướ...
toJjgQgBwx0            Video phân tích và bóc phốt dài gần 1 tiếng củ...
fnTfJ130mjw            Video bình luận mang giọng điệu mỉa mai và hài...
KdiNMS4__w4            Video dài 48 phút của YouTuber Yo Bae bóc trần...
foeGbXU6pGI            Góc nhìn chiêm nghiệm sâu sắc và thẳng thắn củ...
vKhuzVQboe0            Video tóm tắt chi tiết lịch sử cuộc đời Adolf ...
Name: Nội dung chính toàn video, dtype: object

In [22]:
df =  df[['platform', 'video_id', 'video_url', 'video_title',
          'video_core_content','video_target_sentiment','video_highlight','comment']]

In [23]:
df.head()

,platform,video_id,video_url,video_title,video_core_content,video_target_sentiment,video_highlight,comment
0,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,neutral,"Giải thích về trường phái lập thể, các giai đo...",bác pi cát xô là bạn của bác hồ
1,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,neutral,"Giải thích về trường phái lập thể, các giai đo...",cấm sừng nhiều thế
2,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,neutral,"Giải thích về trường phái lập thể, các giai đo...",cho ai chưa biết thì những người đó đều là nic...
3,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,neutral,"Giải thích về trường phái lập thể, các giai đo...",tên bài nhạc là gì vậy mọi người
4,youtube,HyDxRTBnwNM,https://www.youtube.com/watch?v=HyDxRTBnwNM,Huyền Thoại Đa Tình Páp-Lô Pi-Cát-Xô,Video hoạt hình vẽ tay mang phong cách hài hướ...,neutral,"Giải thích về trường phái lập thể, các giai đo...",picasso năm 10 14t đẹp trai vãi

In [24]:
df.to_csv('combined_data.csv', index=False)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7978 entries, 0 to 7977
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   platform                7978 non-null   object
 1   video_id                7978 non-null   object
 2   video_url               7978 non-null   object
 3   video_title             7978 non-null   object
 4   video_core_content      7978 non-null   object
 5   video_target_sentiment  7978 non-null   object
 6   video_highlight         7978 non-null   object
 7   comment                 7975 non-null   object
dtypes: object(8)
memory usage: 498.8+ KB